### ISSUE TITLE
IntelliJ

### ISSUE THREAD

**Issue by unicomp21** [joyent/java-manta#108]
I can't use any version higher than 1.6.0, something is jacked.

**Comment by dekobon** [comment]
@unicomp21 Are you referring to the Java version? IntelliJ is currently on version 15.0.x

**Comment by phillipross** [comment]
possibly referring to java-manta v1.6.0

**Comment by unicomp21** [comment]
I couldn't build the latest, think it was because my maven wasn't new
enough.

**Comment by unicomp21** [comment]
openjdk version "1.8.0_71"
OpenJDK Runtime Environment (build 1.8.0_71-b15)
OpenJDK 64-Bit Server VM (build 25.71-b15, mixed mode)

Apache Maven 3.2.5 (NON-CANONICAL_2015-04-01T06:42:27_mockbuild;
2015-04-01T02:42:27-04:00)
Maven home: /usr/share/maven
Java version: 1.8.0_71, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.71-1.b15.fc22.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.3.5-200.fc22.x86_64", arch: "amd64", family:
"unix"

IntelliJ 15, 143.2287

**Comment by dekobon** [comment]
Hi @unicomp21 

I've just tested with:

Ubuntu 14.04 - OpenJDK installed via the Nix package manager.

```
openjdk version "1.8.0_76"
OpenJDK Runtime Environment (build 1.8.0_76-00)
OpenJDK 64-Bit Server VM (build 25.76-b00, mixed mode)
```
and
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
Maven home: /opt/apache-maven-3
Java version: 1.8.0_76, vendor: Oracle Corporation
Java home: /nix/store/7z8295fdyxnkg3jkp0r7rf1kkqj54i7i-openjdk-8u76b00/lib/openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-77-generic", arch: "amd64", family: "unix"
```

I hate to say - this works for me. Can you give me an error message or a screencap of what is going wrong? How are you attempting to load the project in IntelliJ? I've done all of my development in IntelliJ and I would love to help to get you up and running.

**Comment by unicomp21** [comment]
No worries, I'm going with S3.  Don't want to waste any more of your time.

Thanks,
JD
