### ISSUE TITLE
Can you please release 1.5.1 or 1.5.2?

### ISSUE THREAD

**Issue by maksimov** [joyent/java-manta#14]
dasein-cloud-joyent is being updated to use BountyCastle 1.5.2, however Manta 1.5.0 is using BC 1.4.7. Please help.

**Comment by maksimov** [comment]
*Bump!*

**Comment by maksimov** [comment]
**Bump!**

**Comment by dekobon** [comment]
Cut 1.5.3 release.
Fixed in 42b31d5c501104315a18b3bf923ef17b85072562
