### ISSUE TITLE
have maven enforce consistent license headers

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#158]
This is easy to do with a few different plugins once there are not large diffs in flight.  (With the MPL being file based this become somewhat more important than just consistency.)

**Comment by dekobon** [comment]
I propose we add the following header to the top of each file:
```
/*
 * Copyright (c) 2017, Joyent, Inc. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
```
As suggested [here](https://www.mozilla.org/en-US/MPL/headers/).

We should be able to use this checkstyle module to enforce it: [Header](http://checkstyle.sourceforge.net/config_header.html)

**Comment by cburroughs** [comment]
My understanding of Joyent's policy (and the whole MPL is *file* based thing)  is that we need to preserve the date range where I file already has a date (ie `2012-2014`) and only update as need (January 1st shouldn't come with a bunch of commits that only mess with the copyright date).  There is  a license plugin that zipkin uses that [almost](https://github.com/openzipkin/zipkin/blob/master/pom.xml#L582) does this, but I'm not sure it handles variable inception years.

**Comment by dekobon** [comment]
See related issue #195

**Comment by dekobon** [comment]
I'm closing this because the checkstyle plugin gets us most of the way to validating license headers.
