### ISSUE TITLE
Normalize all parameters and variables that refer to Manta account with different terminology

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#17]

**Comment by phillipross** [comment]
Hi @dekobon 
Can you explain what you had in mind when you filed this issue?  Is this related to the problems that exist between the semantics of **"account"** versus **"user** and the confusion that was created when the RBAC system was implemented?  Thanks!

**Comment by dekobon** [comment]
Hi @phillipross,

Yes, exactly that and the mismatch that I introduced by naming some variables after the environment variables that are used in Manta CLI SDK. I would like to use the same language throughout the entire library.

**Comment by phillipross** [comment]
Gotcha.  I understand and concur :smiley:
I think smart datacenter uses SDC_ACCOUNT and SDC_USER while Manta uses MANTA_USER and MANTA_SUBUSER.  Honestly I was never happy with how they named these, and I dont even think the documentation is consistent in all places, so it begs the question... which language scheme should be used?

**Comment by dekobon** [comment]
Yes. Joyent has been slowly trying to unify their terminology, but there are some historical decisions that are very hard to back out of. Especially, client side environment variables.
In the case of the library, all that I care is that we use the same names internally.

**Comment by dekobon** [comment]
@phillipross Can you send me an email? There's some information that I want to exchange with you that isn't relevant to code/tickets.

**Comment by phillipross** [comment]
absolutely.  email sent.
