### ISSUE TITLE
reduce log level of individual HTTP headers

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#186]
We log almost everything at `DEBUG`, including individual HTTP headers.  This makes it hard to fin relevant information in the logs when running tests, and users might reasonably expect a relevant difference between `DEBUG` & `TRACE`.

**Comment by dekobon** [comment]
This is configurable in the logback-test.xml file. I've had it set to debug level because I've been doing a lot of HTTP inspection. Feel free to set it to INFO or WARN.
