### ISSUE TITLE
AES-CTR Returning Incorrect Byte Range

### ISSUE THREAD

**Issue by uxcn** [joyent/java-manta#207]
The aes-ctr plaintext range translation to ciphertext range is returning incorrect values.  Additionally, validation checks have a couple off by one errors.

The impact is that clients doing random requests on large files may download more data than necessary, or potentially request non-existent data.  The off by one errors are less likely to be run into, but could possibly result in bugs in client's software, transitively.

**Comment by geek** [comment]
@uxcn please provide a test or example to demonstrate the issue.
