### ISSUE TITLE
MantaClient Making Extra HTTP Request For Encrypted Objects

### ISSUE THREAD

**Issue by uxcn** [joyent/java-manta#217]
`MantaClient` is making an extra request to manta for unbounded (and negative) byte range requests (specifically `EncryptionHttpHelper`).  `AesCtrCipherDetails#translateByteRange` requires explicit bounds, and has no mechanism to interpret and compute with implicit bounds.

Similarly, implicit encrypted bounds (e.g. `-n`) need to be translated to account for cipher block sizes, cipher block padding, and authentication bytes.  One way (current) is to request the content length from manta.  Per cipher, all the necessary values should already be known though.

Formally, the equations (negative) for `manta_end_pos` should be...

    manta_end_pos = request_end_pos - (block_size - (request_end_pos % block_size)) - mac_auth_bytes (padded cipher)

    manta_end_pos = request_end_pos - mac_auth_bytes (non-padded cipher)

**Comment by geek** [comment]
@uxcn please point to the code that is making the extra request

**Comment by dekobon** [comment]
Hi @uxcn,

I ran [this](https://github.com/joyent/java-manta/blob/3.0/java-manta-it/src/test/java/com/joyent/manta/client/MantaClientRangeIT.java#L125) integration test in encrypted mode. I only say the following requests during the test run:

```
// Adds the test directory
PUT /elijah.zupancic/stor/java-manta-integration-tests/e1db0f2a-3554-426c-8769-43f79c581720 HTTP/1.1
// Adds the test object
PUT /elijah.zupancic/stor/java-manta-integration-tests/e1db0f2a-3554-426c-8769-43f79c581720780cc180-345b-4e9b-8358-79af27f1dbc7 HTTP/1.1
// Gets a range from the object
GET /elijah.zupancic/stor/java-manta-integration-tests/e1db0f2a-3554-426c-8769-43f79c581720780cc180-345b-4e9b-8358-79af27f1dbc7 HTTP/1.1
// Deletes the test data
PUT /elijah.zupancic/stor/java-manta-integration-tests HTTP/1.1
```

Are we missing a test case in our integration tests?

**Comment by uxcn** [comment]
@dekoban The code I was reading sent a HEAD request if I remember correctly, but I might be wrong.  One of the other things I noticed was that there might be an opportunity for optimization (e.g. no mac for range requests); I need to go over the rfc again though.

I'll try debugging this using the integration tests as soon as I have some spare time.

**Comment by uxcn** [comment]
Hey @dekobon,

I pulled latest from upstream and I ran the specific integration test mentioned above (enabling debug and useEncryption).

Here's the resulting transcript of `http` requests I got...

    PUT /schulz.j/stor/java-manta-integration-tests/b781f0fb-2e38-4ca8-8cbf-566e7d8b8c6722024ff2-3bce-4aaa-a1b4-0674d80e4b0f HTTP/1.1
    HEAD /schulz.j/stor/java-manta-integration-tests/b781f0fb-2e38-4ca8-8cbf-566e7d8b8c6722024ff2-3bce-4aaa-a1b4-0674d80e4b0f HTTP/1.1
    GET /schulz.j/stor/java-manta-integration-tests/b781f0fb-2e38-4ca8-8cbf-566e7d8b8c6722024ff2-3bce-4aaa-a1b4-0674d80e4b0f HTTP/1.1

As best as I can tell, the first request creates the object, the second is the HEAD request for content-length, and the last is the range request.  The second request shouldn't be necessary, and the last may also be requesting more bytes from manta than is necessary.

Digging a bit further, I set a breakpoint in the function and was able to verify that the code is being executed by the integration test.

**Comment by dekobon** [comment]
Could please point out what tests you are running and what lines of code are concerning?

**Comment by uxcn** [comment]
I added a pull request that eliminates the extra http [head](https://github.com/joyent/java-manta/blob/master/java-manta-client/src/main/java/com/joyent/manta/http/EncryptionHttpHelper.java#L381) request (#237).

I ended up going through the extra effort of implementing an *api* for byte ranges, since it seemed like a fairly critical piece of code to make sure was correct.

I think there is one small case that may still not be handled (range request eating into *mac*), but all the integration tests passed when I ran them.
