### ISSUE TITLE
Add configurable buffer size for streaming copy operations

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#223]
Initially I found that smaller buffers provided better performance with cryptographic operations in pure Java. However, upon additional tweaking, I've found that there are performance benefits from tweaking buffer sizes when using libnss.

This issue is to create a configuration parameter that allows the following values to be configurable:
[MantaEncryptedObjectInputStream](https://github.com/joyent/java-manta/blob/3.0/java-manta-client/src/main/java/com/joyent/manta/client/crypto/MantaEncryptedObjectInputStream.java#L68)
[EncryptingEntity](https://github.com/joyent/java-manta/blob/3.0/java-manta-client/src/main/java/com/joyent/manta/client/crypto/EncryptingEntity.java#L195)
[EncryptingPartEntity](https://github.com/joyent/java-manta/blob/3.0/java-manta-client/src/main/java/com/joyent/manta/client/crypto/EncryptingPartEntity.java#L47)

**Comment by cburroughs** [comment]
Do you anticipate *3* different parameters?  Or just a single encrypted buffer param?  If 3, why would a user choose different values?

**Comment by dekobon** [comment]
I wanted you to give it some thought. I *think* one setting would be sufficient because it is sizing the byte array used as a buffer for copying streams. 

According to @arekinath a higher value would yield better performance when interacting with AES-NI. However, since the streams are chained to operations going over a network socket, I'm suspicious about it actually getting better performance with higher values.

**Comment by cburroughs** [comment]
I've extracted `EncryptingEntityBenchmark` into a JMH benchmark and made the `EncryptingEntity` bufferSize configurable.  Looking specifically at encrypting 1 MiB:

```
BC
Benchmark                                (bufferSize)  (encryptionAlgorithm)   Mode  Cnt   Score   Error  Units
EncryptingEntityBenchmark.encryptOneMiB            32   AES128/CTR/NoPadding  thrpt   60  32.694 ± 0.223  ops/s
EncryptingEntityBenchmark.encryptOneMiB            64   AES128/CTR/NoPadding  thrpt   60  33.880 ± 0.303  ops/s
EncryptingEntityBenchmark.encryptOneMiB           128   AES128/CTR/NoPadding  thrpt   60  34.971 ± 0.240  ops/s
EncryptingEntityBenchmark.encryptOneMiB           256   AES128/CTR/NoPadding  thrpt   60  35.856 ± 0.067  ops/s
EncryptingEntityBenchmark.encryptOneMiB           512   AES128/CTR/NoPadding  thrpt   60  35.678 ± 0.336  ops/s
EncryptingEntityBenchmark.encryptOneMiB          1024   AES128/CTR/NoPadding  thrpt   60  35.683 ± 0.321  ops/s

NSS
Benchmark                                (bufferSize)  (encryptionAlgorithm)   Mode  Cnt   Score   Error  Units
EncryptingEntityBenchmark.encryptOneMiB            32   AES128/CTR/NoPadding  thrpt   60  31.865 ± 0.285  ops/s
EncryptingEntityBenchmark.encryptOneMiB            64   AES128/CTR/NoPadding  thrpt   60  38.190 ± 0.477  ops/s
EncryptingEntityBenchmark.encryptOneMiB           128   AES128/CTR/NoPadding  thrpt   60  42.226 ± 0.558  ops/s
EncryptingEntityBenchmark.encryptOneMiB           256   AES128/CTR/NoPadding  thrpt   60  45.204 ± 0.574  ops/s
EncryptingEntityBenchmark.encryptOneMiB           512   AES128/CTR/NoPadding  thrpt   60  44.616 ± 0.095  ops/s
EncryptingEntityBenchmark.encryptOneMiB          1024   AES128/CTR/NoPadding  thrpt   60  45.194 ± 0.310  ops/s
```

I left it running over night and didn't see anything fundamentally different about the other algorithms, or by including encryption+md5.  `-XX:+UseAES -XX:+UseAESIntrinsics` should be the default in JDK8, and explicitly adding them didn't change the results.   It looks like 128 is a reasonable size, 256 might be slightly better.  I don't think the results vary enough to merit a configurable value.

If you translate these number to MiB/s they seem really low to published CPU benchmarks, so I'm sure there are alternative cases (encrypt this one really big file?)  that would yield substantially different results.  But I think that "a bunch of small files MPUed together" is likely to be the most common use case.

**Comment by dekobon** [comment]
Could you rerun this with a 5mb workload? 5mb would be the minimum size for MPU.

**Comment by cburroughs** [comment]
Similar results with 5 MiB.
