### ISSUE TITLE
Problems with handling spaces in file/directory names

### ISSUE THREAD

**Issue by phillipross** [joyent/java-manta#229]
I have files and directory stored in manta that actually have spaces.  It seems node-manta tools allow this (I populated the directories with `muntar`).  The node-manta tools `mls` and `mfind` properly list the files with spaces too:
```
$ mls ~~/stor/ica/images_2016_1022/abh  | grep " " | head -2
Adelaide images/
April 2014/
$ mfind ~~/stor/ica/images_2016_1022/abh  | grep " " | head -2
/philross/stor/ica/images_2016_1022/abh/Adelaide images
/philross/stor/ica/images_2016_1022/abh/April 2014
```
Unfortunately, the java-manta client seems to return these paths with spaces replaced by plus symbols.  Trying to request one of these paths then fails as the path doesn't actually exist with plus sybols... it exists with spaces.

The solution isn't as simple as `URLEncode.encode(path, 'UTF8')` either since that will replace the path separators with %2F.

**Comment by phillipross** [comment]
It appears [MantaUtils.formatPath](https://github.com/joyent/java-manta/blob/master/java-manta-client/src/main/java/com/joyent/manta/util/MantaUtils.java) method is using `URLEncode.encode` which will change the spaces to plus symbols and manta will store the paths with these characters as plus symbols.  I think they should be encoded to `%20` instead of the plus symbol.

The following shows a series of tests I did with curl:
```
$ manta "/$MANTA_USER/stor/java-manta-testing" -XPUT -H"content-type: application/json; type=directory"
$ manta "/$MANTA_USER/stor/java-manta-testing"
$ manta "/$MANTA_USER/stor/java-manta-testing/a b c" -XPUT -H"content-type: application/json; type=directory"
{"BadHTTPRequest": "Request was malformed"}
$ manta "/$MANTA_USER/stor/java-manta-testing/a+b%20c" -XPUT -H"content-type: application/json; type=directory"
$ manta "/$MANTA_USER/stor/java-manta-testing"
{"name":"a+b c","type":"directory","mtime":"2017-04-16T04:44:05.852Z"}
```
In the output, you can see that creating directories with spaces in the path makes manta unhappy.  But plus symbols are indeed stored as plus symbols, while %20 chars are stored as spaces.

**Comment by cburroughs** [comment]
Thank you for the detailed report.  In `master` spaces are now encoded as spaces (and match the node behavior).
