### ISSUE TITLE
Errors on Directory Listing are thrown with missing context

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#232]
In [MantaClient:705](https://github.com/joyent/java-manta/blob/master/java-manta-client/src/main/java/com/joyent/manta/client/MantaClient.java#L705), we catch `UncheckedIOException` exceptions and then rethrow with the cause of the exception. This is a legacy operation that is no longer needed with the improved exception handling in the 3.0.0 version of the SDK.

I reccomend removing the try/catch entirely.

**Comment by cburroughs** [comment]
So, currently if you want to handle listing an object that does not exist you can catch `MantaClientHttpResponseException` (which we throw but without the useful context), and that is what the integration tests do.  Getting an `UncheckedIOException` from a method that is declared to throw a checked `IOException` feels wonky, but there are probably other ways that's possible.  I think  doing we can do the catch-rethrow  and (1) preserve all existing types & behaviors (2) provide context on the exception:

```java
        } catch (UncheckedIOException e) {
            if (e.getCause() instanceof MantaClientHttpResponseException) {
                throw e.getCause();
            } else {
                throw e;
            }
        }
```

**Comment by dekobon** [comment]
That seems sensible, the only gotcha is that we will lose the part of the stack in which the UncheckedIOException was thrown.
