### ISSUE TITLE
Snapshots to sonatype snapshot repo?

### ISSUE THREAD

**Issue by phillipross** [joyent/java-manta#238]
Is there a formal pipeline setup somewhere to publish snapshots to sonatype snapshot repo (or some other repo), maybe out of a CI or something?  or is this done by hand on-demand?

**Comment by cburroughs** [comment]
There isn't currently a CI pipeline for this project and uploads are done by hand as you surmised.  (One would obviously be good to have, but I don't have a timeline for that.)

**Comment by phillipross** [comment]
It looks like Travis is being used for CI... but I saw Jenkins referenced in some pom files.

Is the intention to eventually move from Travis to Jenkins?

**Comment by cburroughs** [comment]
I'd like to eventually have a Jenkins instance doing tests on incoming PRs and snapshot uploads, but I don't want to imply that is a set plan or something that anyone is being actively worked on today.

**Comment by dekobon** [comment]
We are now using TravisCI for unit tests and checkstyle checks. We are using Jenkins for integration tests.

Snapshots are now being created on an as needed basis. In the future, they may be created automatically as part of a build.
