### ISSUE TITLE
Add JCE Policy Key Size Check

### ISSUE THREAD

**Issue by uxcn** [joyent/java-manta#242]
The java-manta api currently assumes the unlimited strength [jce policy](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) is installed, which causes errors at runtime as larger than permitted aes key sizes are requested (e.g. 192/256).

**Comment by tjcelaya** [comment]
What sort of check did you have in mind? It seems like the best we can do is compare the requested key size at config time against [`javax.crypto.Cipher.getMaxAllowedKeyLength`](http://docs.oracle.com/javase/6/docs/api/javax/crypto/Cipher.html#getMaxAllowedKeyLength%28java.lang.String%29) and throw an exception if the requested size is greater than the allowed value. Need to investigate the portability of this solution though.

**Comment by uxcn** [comment]
What I had in mind was moving the error, at very least, earlier in the execution path, and providing a user friendly error message.  In this case, having the jvm catch the error based on the jce policy strength doesn't allow for any unintended consequences, but catching errors earlier can hopefully save people time.

I wrote an example that does this when the associated cipher details are constructed, although it could easily be moved to compile/load time.  The example preserves portability across jvms with and without the unlimited strength jce policy, although there are a number of different approaches possible depending on the needs.

I'm submitting a pull request, although it's a fairly large code, and it potentially changes a public interface people may already be depending on.  Comments are very much welcome.

**Comment by tjcelaya** [comment]
Closed by #244 which was a reengineering of #243. Thanks for helping us make this more explicit!
