### ISSUE TITLE
MantaClient.move() does not support moving a file to a non-existent directory

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#256]
Current move() behavior does not let you move a file into a directory that does not currently exist. However, because S3 and Swift both virtualize directories in the form of keys, many libraries (I'm looking at you Hadoop Filesystem) support move semantics that allow for creating a directory structure when moving a file.

**Comment by cburroughs** [comment]
Stepping back a bit, why is this a desirable feature? It looks like another sharp tool to shoot yourself in the foot with.

I'm also not sure it is the default behavior I would expect as a user:
```
$ mv foo /tmp/does/not/exist
mv: cannot move ‘foo’ to ‘/tmp/does/not/exist’: No such file or directory
```

**Comment by dekobon** [comment]
This covers a gap for users / third-party libraries integrating. S3 virtualizes a file system by storing keys with path separators, Manta does not. This means that adding an object to a directory that doesn't exist is essentially just adding a key. We don't have a way to fill that gap other than this functionality.
