### ISSUE TITLE
Clean up checkstyle

### ISSUE THREAD

**Issue by phillipross** [joyent/java-manta#30]
The existing checkstyle setup should be cleaned up and more standardized.  The rules should be replaced with more standard conventions as a base (sun_checks) and progressively tweaked with project-specific customizations.

**Comment by phillipross** [comment]
Merged PR #32 to begin this work.

**Comment by phillipross** [comment]
Changes to manta client and httpsigner are completed, but not reviewed yet.
Changes to checkstyle.xml have been made, but config package still needs to be updated.

**Comment by dekobon** [comment]
Looks good to me. :+1: 

What's Puppy Crawl?

**Comment by phillipross** [comment]
I guess Puppy Crawl is/are/was/were the developer(s) of the actual checkstyle component.

I had to bump up the version of that component since the maven plugin was referring to an older version which didn't know to skip over serialVersionUID fields when looking for non-javadoced members of a class.

Thanks for looking at these changes... I'll merge PR #36  into the checkstyle branch.  If you're doing your checkstyle work directly on the joyent repo checkstyle branch, please be sure to pull/merge to get the latest updates from PR #36
