### ISSUE TITLE
Missing ETag from ServerSideMultipartManager#uploadPart should throw?

### ISSUE THREAD

**Issue by tjcelaya** [joyent/java-manta#305]
Not sure how useful it is to have a `MantaMultipartUploadPart` with a null etag, [yet we allow it for some reason](https://github.com/joyent/java-manta/blob/6377eb623f4ce177e13dfe8275d18b6b69ead754/java-manta-client/src/main/java/com/joyent/manta/client/multipart/ServerSideMultipartManager.java#L344).

Why is this not a runtime exception?

**Comment by dekobon** [comment]
@jordanhendricks Do you have any thoughts about whether the client should or shouldn't error on a missing e-tag?

**Comment by tjcelaya** [comment]
Discussed offline, we should always require the etag.

**Comment by tjcelaya** [comment]
Resolved by #318
