### ISSUE TITLE
Factor out HttpSigner into separate repo

### ISSUE THREAD

**Issue by phillipross** [joyent/java-manta#31]
A [new repo](https://github.com/joyent/java-http-signer) has been setup for this.

It would probably be better to cleanup the build/release/document/conventions here before factoring this out into the separate repo.  Dependent issues include #29 & #30

**Comment by dekobon** [comment]
In preparation for #44, this repo should probably be an Apache HTTP Client plugin: http://hc.apache.org/httpclient-3.x/authentication.html#Authentication_Schemes

**Comment by phillipross** [comment]
+1 :+1:
