### ISSUE TITLE
cli get-file hard to use for large/binary files

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#312]
Because java-manta remains the only mainline implementation of client-side-encryption, I have ended up using the cli get/put subcommands when I need to do something short of "write a java program".  There are a few issues:

 * The various messages like "Creating connection configuration" make it hard to get at the exact byte-for-byte data.
 * Loading everything into memory doesn't work for large files.
 * no way to just write to a file (a la `mget -O`)
 * I'm not sure `getAsString` is going to do what we want for raw binary data.

**Comment by dekobon** [comment]
@geek What is the status on the node support for CSE?

**Comment by geek** [comment]
@dekobon it works fine in my branch but is waiting on approval for merging into the mainline

**Comment by cburroughs** [comment]
Still https://cr.joyent.us/#/c/1110/ ?
