### ISSUE TITLE
Support Expect header for PUT object requests

### ISSUE THREAD

**Issue by kellymclaughlin** [joyent/java-manta#314]
While investigating a muskie connection leak issue I noticed that Java client does not use an `Expect` header by default for PUT object requests or even have helpers in `MantaHttpHeaders` for the `Expect` header. 

It just so happens that sending along an `Expect: 100-continue` with a PUT request avoids the Manta bug I was investigating, but also avoids shoving a bunch bytes over the network in a case when Manta was in a degraded state and would return an error.

I would argue in favor of sending along this header by default for PUT object requests if no explicit headers are given, but at very least some helpers to facilitate using it in `MantaHttpHeaders` seem like a nice thing to have.

I'm happy to work on a PR for this, but wanted to have some discussion first to see what others thought should actually be done.

**Comment by tjcelaya** [comment]
There is functionality in [Apache HttpClient](http://hc.apache.org/httpclient-3.x/performance.html#Expect-continue_handshake) to explicitly support this so it should be straightforward to support.
