### ISSUE TITLE
would like integration tests to use a dedicated per-run directory

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#320]
Currently we place all of the integration tests objects under `~~/stor/java-manta-integration-tests` with UUIDs to ensure unique object names.  All objects should be cleaned  up after tests complete, but due to test failures, bugs in the tests themselves (#319), job cancellations, etc this is not always the case.

In one environment, I would like to be able to `mrm -r ~~/stor/java-manta-integration-tests` because the test account is using an appreciable amount of sapce, but there are a few objects I need for ongoing debugging.  It would be easier to find the files I need, and to delete everything else, if each invocation of the integration tests used it's own directory (ie `~~/stor/java-manta-integration-tests/$UUID`).

**Comment by tjcelaya** [comment]
How is this different from #319 ?

**Comment by cburroughs** [comment]
#319 is for  `~~/stor/java-manta-integration-tests/$UUID_PER_CLASS` not being used correctly.

This proposes changing to `~~/stor/java-manta-integration-tests/$UUID_PER_RUN/$UUID_PER_CLASS`.  Although as I look at that it might be nice to change from `$UUID_PER_CLASS` to `$PackageName`, since we would then only need to be unique per run.

**Comment by tjcelaya** [comment]
Sorry I missed the distinction. The PR for #319 centralizes path generation
so it should pave the way for addressing this issue. I'd actually thought
about proposing a change like this one at one point so I'm definitely on
board.
