### ISSUE TITLE
compiler warnings: some AutoClosable class could throw InterruptedException

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#322]
```
[WARNING] /home/jcsb/src/manta/java-manta/java-manta-client/src/main/java/com/joyent/manta/http/StandardHttpHelper.java:[57,8] auto-closeable resource com.joyent.manta.http.StandardHttpHelper has a member method close() that could throw InterruptedException
[WARNING] /home/jcsb/src/manta/java-manta/java-manta-client/src/main/java/com/joyent/manta/http/EncryptionHttpHelper.java:[77,8] auto-closeable resource com.joyent.manta.http.EncryptionHttpHelper has a member method close() that could throw InterruptedException
[WARNING] /home/jcsb/src/manta/java-manta/java-manta-client/src/main/java/com/joyent/manta/http/HttpHelper.java:[42,8] auto-closeable resource com.joyent.manta.http.HttpHelper has a member method close() that could throw InterruptedException
[WARNING] /home/jcsb/src/manta/java-manta/java-manta-client/src/main/java/com/joyent/manta/http/MantaConnectionContext.java:[19,8] auto-closeable resource com.joyent.manta.http.MantaConnectionContext has a member method close() that could throw InterruptedException
```

From <https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html>

**Implementers of this interface are also strongly advised to not have the close method throw InterruptedException**

**Comment by dekobon** [comment]
I've been insofar unable to remove that warning with the approaches that I've tried. I would love for someone else to take a crack at it.

**Comment by cburroughs** [comment]
As described oh so tersely at <https://bugs.openjdk.java.net/browse/JDK-8155591>, this warning isn't very precise.  We are hitting it because `void close() throws Exception` means that `InterruptedException` (a child of `Exception`) "could" be thrown... which is the signature of `AutoCloseable`.  It appears that the expectation is that anything implementing or subinterfacing  `AutoCloseable` would explicitly list something more specific than `Exception`.  I couldn't get `SurpressWarnings` to cover this up (it appears the set of things you can suppress is not the same as the set of all warnings).

Options:
 * (A) Fiddle with a bunch of method signatures to make this go away.  I think that would always look confusing, not fix any real bugs, and involve changing public signatures.
 * (B) Compile with `-Xlint:all,-try`, which I think will keep all warnings except the "try" ones.  I'm unsure what other warnings that includes <https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html#BHCJCABJ>
 * (C) Do nothing and have routinely ignored warnings scrolling by during compilation.

None of those are great, (B) might be the least bad?

**Comment by dekobon** [comment]
Aren't the typical "try" warnings useful? If so, I would lean towards (C). However, infuriating that may be.

**Comment by cburroughs** [comment]
I'm not sure what all of the "try" warnings are, but yes I think the others are probably useful.

I suppose at the least we could add comments to relevant methods so that the next time someone tries to cleanup warnings they are saved some time.

**Comment by dekobon** [comment]
:+1:
