### ISSUE TITLE
Excessive Logging During Tests

### ISSUE THREAD

**Issue by tjcelaya** [joyent/java-manta#324]
There is a flood of log output that occurs when running the test suite which provides very little useful information. Thousands of lines like the following which don't provide any context and make it more difficult to find actual test failures:

- `[main] DEBUG com.joyent.manta.client.crypto.EncryptingEntityHelper - Creating new OutputStream for multipart [class org.bouncycastle.jcajce.io.CipherOutputStream]`
- `[main] DEBUG com.joyent.manta.client.crypto.EncryptingEntity - HMAC: 699884b09e0fe8f6f467a29cf49f89b7`
- `Exception thrown: Unable to authenticate object's ciphertext. It failed the authenticity checksum. Check to see that the object's binary data hasn't been modified.` (this is intentional, but it looks like a test failure if you're scanning the output)

I'd like to propose the following options:

- raise the default logging level to `INFO` or `WARN` during testing
- change these logging statements to a higher log level if they are still desired
- remove the logging where it doesn't actually provide any value, e.g. `Creating new OutputStream`

**Comment by cburroughs** [comment]
Thanks for bringing this up.  My inclination is to leave the testing log level at `DEBUG`.  If a test fails (especially in a transient fashion!) I'd err on the side of retaining information to figure out why.

For these offending lines, I think a combination of removing them or setting them to `TRACE` is fine.  As you mentioned it looks like a few lines are responsible for the vast majority of output.

**Comment by cburroughs** [comment]
Is this complete with #327 in master?

**Comment by tjcelaya** [comment]
Yep I just forgot to close this out yesterday, thanks for the reminder!
