### ISSUE TITLE
testng encryptionCipher parameter does not appear to do anything

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#336]
Running with a scaled down testng xml file:

```
    <test name="Manta Client Integration Tests [AES128/CBC Encrypted]">
        <parameter name="usingEncryption" value="true"/>
        <parameter name="encryptionCipher" value="AES128/CBC/PKCS5Padding"/>
        <packages>
            <package name="com.joyent.manta.client.*" />
        </packages>
    </test>
```

In `IntegrationTestConfigContext.enableTestEncryption` from simple `println` additions, the value of `encryptionCipher`  is always `null` and `cipherDetails.getCipher().getAlgorithm()` is `AES/CTR/NoPadding`.  Looking at the class more broadly, there is code to check system properties and environmental variables, but I don't see anything invoking the testng parameter system.

In light of #155 #154 #202 #201 I'm not sure what the expected status of anything other than the default is.

**Comment by dekobon** [comment]
I believe that at some point we refactored out most of the TestNG parameters. There must have been a mistake made where we left out the encryptionCipher as a result.

**Comment by tjcelaya** [comment]
A lot of tests are explicitly duplicated for multiple encryption ciphers, perhaps some classes were refactored to be more explicit about multi-cipher testing and others were forgotten? I'm under the impression it would be better to simplify the test cases and utilize parameters more heavily, but it sounds like there was an effort to do the opposite at one point. I would be happy to do the refactoring to consolidate on a single approach, I think the `reallyLongTestNameThatHappensToIncludeAesCtr192atTheEnd` pattern makes it more likely to forget specific ciphers than explicitly listing them in `testng.xml`.
