### ISSUE TITLE
Attempt to skip redundant `putDirectory` calls if possible

### ISSUE THREAD

**Issue by tjcelaya** [joyent/java-manta#371]
As a performance optimization we'd like to avoid `PUT` on directories that already exist.

**Comment by cburroughs** [comment]
I don't think we had a ticket for it, but I think when this came up during a manta call @davepacheco had some a algorithmic commentary.  In particular, if the worst case becomes O(depth) GETs + O(depth) PUTs, are we sure this is a win in aggregate?

**Comment by tjcelaya** [comment]
The ticket title is too specific about implementation details, I'll clear that up.

**Comment by tjcelaya** [comment]
As suggested by @dekobon it might be better to work from the requested directory up toward the root of the tree. I'm still fiddling with different solutions and will present options once I flesh them out.

**Comment by tjcelaya** [comment]
Following up from the previous comment, muskie logs indicated that `HEAD` and `PUT` requests to missing parent directories follow the same code paths, so there are no savings when checking directories with `HEAD`. Attached is debug logging from the latest commit to #372. The search algorithm is described in the class JavaDoc for `ProvingDirectoryCreationStrategy` but copied here for ease of consumption:

A strategy for creating directories similar to binary/interpolation search. The general approach is
as follows:
- Build prefix paths to desired directory
- Drop system paths (/USER and /USER/SYSTEM_DIR)
- Set up:
  - `idx` is the index of the current directory to probe
  - `min` is the index of the root-most directory we need to check
  - `max` is the index of the deepest directory we need to check
  - `descending` whether or not the next probe should be deeper in the hierarchy
- Loop the probing phase, updating the above variables along the way:
  - Choose the directory halfway between the root-most directory that might need to be created
  - and the desired directory
  - If the directory creation was redundant, update `min` and set `descending` to true
  - Otherwise, if the directory creation failed, update max to point to the failed probe and set `descending` to false
  - Calculate the jump length based on the distance between `min` and `max`
  - Add (or subtract, if `descending` is false) the jump distance from the current index
- Exit the above loop if any of the following conditions are met:
  - The leaf directory was created (this is unlikely)
  - The last PUT attempted actually created a new directory (it can have no children)
  - The jump distance was zero, i.e. `floor((max - min) / 2) == 0` since `min` and `max` are too close together
- Create remaining directories normally

Results attached in the following gist.

https://gist.github.com/tjcelaya/e02eec9d7dda2d0ed648f3c0792df360

The above gist is the output #372 so far. For small directory paths (<10 levels) a binary search of the existing intermediate directories _could_ add up to 2 extra calls.

Other discussions have talked about caching directories which we've successfully used, e.g. a successful `PUT` to `/user/stor/foo/bar/baz` would cache the fact that `/user/stor/foo/bar` exists. Balancing memory consumption and concurrency requirements becomes a challenge when there are thousands of threads independently working on different files so that doesn't seem straightforward either. A general-purpose cache would be either extremely memory-hungry or extremely poorly-performing. Alternatively we could make it tunable for different use-cases (e.g. limit number of entries, depth of entries, etc.).

**Comment by tjcelaya** [comment]
Following up with actual implementation description:

To ease usage of this optimization and simplify implementation, the final decision was to create a new configuration parameter: `manta.skip_directory_depth` / `MANTA_SKIP_DIRECTORY_DEPTH`

We've opted to minimize the amount of probing (the new implementation can add at most 1 failed request) because while the `ProbingDirectoryCreationStrategy` described above was more dynamic, it could also add failed requests proportional to the logarithm of the final directory depth.

When a recursive call to `putDirectory` occurs we will check the value of that configuration setting and invoke one of two strategies, both described in the context of creating the `/user/stor/foo/bar/baz/quux` directory with `MANTA_SKIP_DIRECTORY_DEPTH` set to 2:

- DepthSkipping:
  - Check if the number of intermediate directories is less than or equal to the skip depth, if so, invoke the Complete strategy and exit. In this example we do not switch strategies because the skip depth of 2 is greater than the number of intermediate directories, 4 (`/foo`, `/foo/bar`, `/foo/bar/baz`, `/foo/bar/baz/quux`)
  - Attempt to create the directory at the skip depth. In our example, this would equate to:
    - `PUT /user/stor/foo/bar/baz`
  - If the skip attempt was successful, continue creating the remaining directories until reaching the requested directory. In our example this leaves just the final directory:
    - `PUT /user/stor/foo/bar/baz/quux`
  - If the skip attempt was unsuccessful, invoke the Complete strategy and exit.

- Complete:
  - Create every writeable directory between the root and the requested directory. For example, when recursively creating `/user/stor/foo/bar/baz` the following calls will occur:
    - `PUT /user/stor/foo`
    - `PUT /user/stor/foo/bar`
    - `PUT /user/stor/foo/bar/baz`
    - `PUT /user/stor/foo/bar/baz/quux`
