### ISSUE TITLE
ServerSideMultipartManager#uuidPrefixedPath assumes too much

### ISSUE THREAD

**Issue by tjcelaya** [joyent/java-manta#384]
I missed this method when assessing the impact of MANTA-3427. Fortunately the server falls back to checking the old path format so requests using the old prefix length do still succeed. It's used very sporadically (1 in `getStatus` and 2 integration tests) but we should still remove this package-private method at some point.

**Comment by dekobon** [comment]
This issue is now obsolete. See #451
