### ISSUE TITLE
HTTP Content-Type header is not being read correctly

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#39]
The contentType bean on MantaObject is being consistently set to null. You can repro this by reading a directory.

**Comment by phillipross** [comment]
@dekobon This is a bug, right?  Something that a test in the test suite should be detecting if there were proper assertions in place?

**Comment by dekobon** [comment]
Yes, this is a bug that I found when writing nio2 tests.

**Comment by dekobon** [comment]
I think we can tackle it easily when we add apache commons httpclient.

**Comment by phillipross** [comment]
Fixed by 115af9a71ce18360886603127db925ea336754c9
Merged to master on 04c1df4e76642c51e1b252526818d6569f0e2e50
