### ISSUE TITLE
Reject non-ascii values in Manta Headers

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#395]
Due to MANTA-3527, objects can go into a state where they cannot be read if the header was written with a non-ascii value. We should add a guard clause that tells users that a non-ascii value was invalid and guide them to encode it.

**Comment by tjcelaya** [comment]
> tells users that a non-ascii value was invalid and guide them to encode it.

Just to be clear we want to throw an exception since this effectively makes the object inaccessible right? The ticket description implies this could be fixed server-side by a node.js update but I presume we would want to entirely forbid people from getting themselves into this situation.

**Comment by tjcelaya** [comment]
Also, "Manta Headers" -> "Metadata" ?

**Comment by dekobon** [comment]
> Just to be clear we want to throw an exception since this effectively makes the object inaccessible right? The ticket description implies this could be fixed server-side by a node.js update but I presume we would want to entirely forbid people from getting themselves into this situation.

Yes, we want to forbid them. Additionally, we want to suggest to them to encode the data in someway that makes it 7-bit safe. Like UUENCode, URLEncode or mime64.

> Also, "Manta Headers" -> "Metadata" ?

Yes.
