### ISSUE TITLE
Confused by Javadoc of MantaClients.put* methods, what is using the default JVM encoding?

### ISSUE THREAD

**Issue by gamlerhart** [joyent/java-manta#405]
Example, one of the most basic [MantaClient.put(String path, byte[] bytes)](https://github.com/joyent/java-manta/blob/master/java-manta-client-unshaded/src/main/java/com/joyent/manta/client/MantaClient.java#L1383) method. The Javadoc reads:

> Copies the supplied byte array to a remote Manta object at the specified
> path using the default JVM character encoding as a binary representation.

I am confused by this. What is encoded with the JVM default character encoding? I expect no encoding going on here. The path ends up in the URL and should be URL encoded. The bytes as the raw body and I don't expect any encoding. Any default headers also should have no header.

This goes on for many other MantaClient.put flavors. 

There are the [MantaClient.put(String path, String string) ](https://github.com/joyent/java-manta/blob/master/java-manta-client-unshaded/src/main/java/com/joyent/manta/client/MantaClient.java#L1251)favors. In those cases there is a encoding needed for the string, so there this info makes sense.

So, overall it looks to me like it is an documentation mistake?

**Comment by tjcelaya** [comment]
Looks like the javadoc was copied from `put(String, String,
MantaHttpHeaders)`. I'll work on correcting these JavaDocs, but if you want
to submit a PR with clarification for the `byte[]` body methods I'd be
happy to accept a fix.

**Comment by gamlerhart** [comment]
My blunt changes to review: https://github.com/joyent/java-manta/pull/406
