### ISSUE TITLE
Recursive delete fails to work when retries=0

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#407]
When recursive delete is attempting to delete each individual entry, it wraps the operation in a for loop with the exit condition being `i < config.getRetries()`, so a retry value of 0 will mean that the operation is never run. See: [MantaClient.java:369](https://github.com/joyent/java-manta/blob/ec6d79f8a8c68b344aac7bf465ba2e22f0bb14ee/java-manta-client-unshaded/src/main/java/com/joyent/manta/client/MantaClient.java#L369):
```java
/* We go through every remaining directory and file attempt to
 * delete it even though that operation may not be immediately
 * successful. */
toDelete.forEachOrdered(obj -> {
   for (int i = 0; i < config.getRetries(); i++) {
...
}
```

**Comment by tjcelaya** [comment]
I presume our solution would look something like the following?

```
final boolean retryIndefinitely = config.getRetries() == 0;
...
toDelete.forEachOrdered(obj -> {
    for (int i = 0; retryIndefinitely || i < config.getRetries(); i++) {
```

I'm writing up a test for this now, will most likely have a PR ready tomorrow.
