### ISSUE TITLE
Formatting the Mbean attribute 999thPercentile for the metric object requests-$METHOD

### ISSUE THREAD

**Issue by 1010sachin** [joyent/java-manta#436]
The attribute reported as 999thPercentile for all the requests object seems to be confusing. Can it be formatted to  something that can make it easily distinguishable from 99thPercentile like 99.9thPercentile or 99_9Percentile?
<img width="991" alt="screen shot 2018-10-15 at 2 05 12 pm" src="https://user-images.githubusercontent.com/37811940/46978579-31872100-d084-11e8-9c67-89b9309b9152.png">

**Comment by nairashwin952013** [comment]
@dekobon After reviewing this issue further, I found out that the 999th Percentile Attribute reported for the metric object requests-$METHOD is the default ```name``` value provided by the java lib. for jmx-reporter in package:```com.codahale.metrics.jmx;```, so do you want me to update/override this attribute-name while we are building the ```jmx-reporter``` [here](https://github.com/joyent/java-manta/blob/master/java-manta-client-unshaded/src/main/java/com/joyent/manta/client/MetricReporterSupplier.java#L82)
