### ISSUE TITLE
Error occurred with 'mvn clean install' against the java-manta directory in the MantaObjectOutputStreamIT test class within java-manta-it sub-module 

### ISSUE THREAD

**Issue by nairashwin952013** [joyent/java-manta#437]
This error happened inside the mentioned test class within the given location specifically under the method canUploadSmallStringWithErrorProneName() when the close method on the output stream is called. the stack trace for the error is attached.
<img width="3165" alt="screen shot 2018-11-05 at 3 05 06 pm" src="https://user-images.githubusercontent.com/23692852/48294274-14056700-e438-11e8-8e1b-a13be13881b2.png">

**Comment by dekobon** [comment]
This was probably an issue with an unreliable network connection. Closing until more evidence is available.
