### ISSUE TITLE
Server-side MPU returns a committed result but it is parsed as COMMITTING

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#452]
We currently parse the result of a MPU operation's status as follows:
```java
        if (result.equalsIgnoreCase("aborting")) {
            return MantaMultipartStatus.ABORTING;
        }
        if (result.equalsIgnoreCase("aborted")) {
            return MantaMultipartStatus.ABORTED;
        }
        if (result.equalsIgnoreCase("committing")) {
            return MantaMultipartStatus.COMMITTING;
        }
        if (result.equalsIgnoreCase("committed")) {
            return MantaMultipartStatus.COMMITTING;
        }
```
Both `committing` and `committed` return the same value due to a limitation of MPU at the time of its initial development. The Manta Java SDK was not updated to convert `committed` to the `COMPLETED` enum when the server-side functionality was finished.

**Comment by nairashwin952013** [comment]
Fixed in ```3f7b4d26e86eceb54d102e2ed72a084043ef324e```
