### ISSUE TITLE
Allow for authentication to be disabled in CSE

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#465]
Currently, `com.joyent.manta.config.EncryptionAuthenticationMode` supports two modes: `Optional` and `Mandatory`. This change would add a third mode - `Disabled`. This mode would disable checksum verification of ciphertext.

**Comment by nairashwin952013** [comment]
Also, we want the ```DEFAULT_MODE = Mandatory``` ?

**Comment by dekobon** [comment]
No, by choosing `Mandatory` it will change the default behavior and act like an API change. Additionally, it will turn off functionality like HTTP range requests with CSE.
