### ISSUE TITLE
NoApiServersAvailable is not present in MantaErrorCode enums

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#470]
There is no value for `NoApiServersAvailable` in the `MantaErrorCode` enum.

**Comment by nairashwin952013** [comment]
After further reviewing this issue and consulting with @IanWyszynski and @jclulow, I found out that the ```MantaErrorCode``` enum should include the ```408-Error``` from [this repository](https://github.com/joyent/muppet/tree/94f465008b300752eb1b72585edb267139ea723f/etc) ending in ```.http```. Also, ```400``` and ```503``` have already been included in the enum values:```BAD_REQUEST_ERROR``` and ```SERVICE_UNAVAILABLE_ERROR``` [here](https://github.com/joyent/java-manta/blob/master/java-manta-client-unshaded/src/main/java/com/joyent/manta/exception/MantaErrorCode.java#L33).

Furthermore, enum values corrected for: 

- ```409:ENTITY_EXISTS_ERROR```[here](https://github.com/joyent/manta-muskie/blob/master/lib/errors.js#L168). 
- ``` 400:INVALID_PATH_ERROR```[here](https://github.com/joyent/manta-muskie/blob/master/lib/errors.js#L304). 
- ```JOB_STATE_ERROR``` [here](https://github.com/joyent/manta-muskie/blob/master/lib/errors.js#L345). 
- ```LINK_REQUIRED_ERROR``` [here](https://github.com/joyent/manta-muskie/blob/master/lib/errors.js#L398).  
- [MAX_CONTENT_LENGTH_ERROR](https://github.com/joyent/manta-muskie/blob/master/lib/errors.js#L420). 
- [MULTIPART_UPLOAD_CREATE_ERROR](https://github.com/joyent/manta-muskie/blob/master/lib/errors.js#L450).

 
Additional Values Edited by referring [source file](https://github.com/joyent/manta-muskie/blob/master/lib/errors.js). 

Values added for:

- [INVALID_ALGORITHM_ERROR](https://github.com/joyent/manta-muskie/blob/master/lib/errors.js#L198). 
- [SHARDS_EXHAUSTED_ERROR*](https://github.com/joyent/manta-muskie/blob/master/lib/errors.js#L408). 

Other Values Added by referring [source file](https://github.com/joyent/manta-muskie/blob/master/lib/errors.js).

**Comment by dekobon** [comment]
Additionally, I discovered that the error code: `SnaplinksDisabledError` has also not been added to the list of error codes.

**Comment by nairashwin952013** [comment]
Being fixed by PR #501
