### ISSUE TITLE
Standardize .equals() and .hashCode() behavior

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#477]
Across the entire project we use different naming conventions and procedures for `.equals()` and `.hashCode()` methods. We should make all of the code for these methods consistent.

**Comment by nairashwin952013** [comment]
It is typically preferable to use the Arrays method when passing it a construct that is already known to be a Java array and to use the Objects method for situations where the values are being passed in a comma-separated combination without explicit array syntax being required. Referring to [EncryptionStateSnapshot.java#L95](https://github.com/joyent/java-manta/blob/master/java-manta-client-unshaded/src/main/java/com/joyent/manta/client/multipart/EncryptionStateSnapshot.java#L95)

**Comment by nairashwin952013** [comment]
Hence, I would suggest against standardizing ```.hashCode()``` , since the current code procedures are *optimal* with their implementations. For more details, Kindly refer [this](https://dzone.com/articles/arrayshashcode-vs-objectshash) page.

**Comment by dekobon** [comment]
Ok. Hashcodes are good then.

Now, what about `.equals()`? We probably want to use the Java 7+ method of generating equals that uses `Object.equals()` for properties that could be null and `.equals()` for non-nullable properties. IntelliJ does a reasonable job of auto-generating these equals methods. However, it doesn't do a good job of generating them such that they work with checkstyle unless you mess with the IntelliJ code style settings.
