### ISSUE TITLE
Investigate removing Apache Commons Collections Dependency

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#481]
Few classes imported from Apache Commons Collections are used. We should investigate importing only what we need or some other solution in order to remove a dependency out of our graph.

**Comment by nairashwin952013** [comment]
Is the dependency being removed to consider better alternates?

**Comment by dekobon** [comment]
No. The idea is to have less overall dependencies, so that the library requires less maintenance.

**Comment by nairashwin952013** [comment]
Do you think a ```Google Core Collections Library``` will be a better alternative or the ```Java Utils Collections Library``` ?

**Comment by dekobon** [comment]
No, the idea was to remove the library so that we had one less library to support. I think a good next step is to analyze what classes are used from that library and add that as a comment here.

**Comment by nairashwin952013** [comment]
I already had done that should have recorded and noted it down somewhere. 

Anyways some of the classes that directly use the data structures defined in this dependency are ```MantaHttpHeaders.java, LookupMap.java, CreateMPURequestBody.java, EncryptedMetadataUtils.java including some related unit-tests and integration-tests```

**Comment by dekobon** [comment]
We only care about non-test code. What classes in apache commons collections are those classes about using?

**Comment by nairashwin952013** [comment]
- MapIterator, CaseInsensitiveMap : MantaHttpHeaders.java.
- CaseInsensitiveMap, UnmodifiableMap : LookupMap.java.
- Predicate, PredicatedMap, CaseInsensitiveMap: MantaMetadata.java.
- CaseInsensitiveMap : EncryptedMetadataUtils.java.
- CaseInsensitiveMap : CreateMPURequestBody.java.
