### ISSUE TITLE
TLS Cert import documentation is missing steps

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#482]
The documentation here: https://github.com/joyent/java-manta/blob/master/FAQ.md#how-can-i-set-up-the-client-to-connect-to-a-personal-manta-deployment

Is missing an explanation saying that you have to name your host in your `/etc/hosts` file to the value returned from the `CN` fields like:
```
Owner: CN=manta.us-northwest.headnode.tatsumaki.local, OU=manta, O=Joyent, ST=CA, C=US
```

Additionally, the document is missing the step to convert your cert to x509 format:
```
openssl x509 -in manta-ssl.crt -out manta-ssl.pem
```

**Comment by nairashwin952013** [comment]
This `issue` is currently being tracked by #516 .
