### ISSUE TITLE
Create Test Groups that include Heavyweight Tests that are not run by default

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#483]
The heavyweight tests can be scheduled to be run nightly.

**Comment by nairashwin952013** [comment]
Do I enable this Test Group: ```nightly``` as false by ```default``` in the SDK ?

**Comment by dekobon** [comment]
Yes, that would make sense. We should document the test behavior in the docs.

**Comment by nairashwin952013** [comment]
This issue is being currently tracked by PR #504 in the ```fix-483-testgroups``` branch.
