### ISSUE TITLE
Create configuration setting that allows for disabling content-type autodetection

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#488]
The class `com.joyent.manta.http.ContentTypeLookup` is always invoked when `PUT`ing files into Manta. This feature would add the ability for the user to explicitly disable content type detection based on the data being uploaded.

**Comment by nairashwin952013** [comment]
Under what conditions(data-types ?) generally should we opt to disable auto-detection ?

**Comment by dekobon** [comment]
When the user enables a setting to disable it.
