### ISSUE TITLE
http headers should be case-insensitive

### ISSUE THREAD

**Issue by phillipross** [joyent/java-manta#66]
According to the [RFC](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

It would be a good idea to verify that the manta service also behaves in a way that treats the headers as case-insensitive, then validate that java-manta evaluation of header/metadata key names is also case-insensitive, especially when dealing with "m-" custom metadata.

**Comment by phillipross** [comment]
Good to know... maybe this can be pointed out in javadoc or readme or something.  There's a follow up question I had as to whether or not there can be more than one "m-" header with the same name.  I'm actually testing this right now.

**Comment by phillipross** [comment]
After working with the raw headers, it appears that custom "m-" headers can not have multiple values with the same header name.  When writing to the manta service with multiple values in a List and then reading from the manta service, only the first header value was stored.

I don't know what the probability might be of the manta service changing these semantics in the future, but it might be worth enforcing these semantics in the MantaMetadata class if they are not already enforced, and then documenting them.

**Comment by dekobon** [comment]
The semantics are enforced when we insert the metadata into the headers in the the method `MantaHttpHeaders.putAllMetadata()`. As for documentation, I will explicitly call it out.

**Comment by dekobon** [comment]
I see the probability of changing the behavior of header-based metadata to be very low.

**Comment by phillipross** [comment]
Perfect, thanks!
